GeekShopping/GeekShopping.Web/Controllers/CartController.cs
using GeekShopping.Web.DTO;
using GeekShopping.Web.Interfaces;
using GeekShopping.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace GeekShopping.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartRepository _cartRepository;
        private readonly ICouponRepository _couponRepository;
        private readonly IOrderRepository _orderRepository;

        public CartController(
            ICartRepository cartRepository,
            ICouponRepository couponService,
            IOrderRepository orderRepository
        )
        {
            _couponRepository = couponService;
            _cartRepository = cartRepository;
            _orderRepository = orderRepository;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userId = User.Claims.Where(u => u.Type == "sub")?.FirstOrDefault()?.Value;

            var cart = await _cartRepository.GetCartByUserId(userId);

            if (cart.CartHeader != null)
            {

                if (!string.IsNullOrEmpty(cart.CartHeader.CouponCode))
                {
                    var coupon = await _couponRepository.GetCoupon(cart.CartHeader.CouponCode);

                    if (coupon?.Code != null)
                    {
                        cart.CartHeader.DiscountAmount = coupon.DiscountAmount;
                    }
                }
                foreach (var detail in cart.CartDetails)
                {
                    cart.CartHeader.PurchaseAmount += (detail.Product.Price * detail.Count);
                }

                cart.CartHeader.PurchaseAmount -= cart.CartHeader.DiscountAmount;
            }

            return View(cart);
        }

        [Authorize]
        public async Task<IActionResult> Remove(long id)
        {
            var response = await _cartRepository.RemoveCartItem(id);

            if (response) return RedirectToAction(nameof(Index));

            return View();
        }

        [Authorize]
        [HttpPost("ApplyCoupon")]
        public async Task<IActionResult> ApplyCoupon(CartDTO cart)
        {
            var userId = User.Claims.Where(u => u.Type == "sub")?.FirstOrDefault()?.Value;
            var response = await _cartRepository.ApplyCoupon(userId, cart.CartHeader.CouponCode);

            if (response) return RedirectToAction(nameof(Index));
            return View();
        }

        [Authorize]
        [HttpPost("RemoveCoupon")]
        public async Task<IActionResult> RemoveCoupon()
        {
            var userId = User.Claims.Where(u => u.Type == "sub")?.FirstOrDefault()?.Value;

            var response = await _cartRepository.RemoveCoupon(userId);

            if (response) return RedirectToAction(nameof(Index));
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            var userId = User.Claims.Where(u => u.Type == "sub")?.FirstOrDefault()?.Value;

            var cart = await _cartRepository.GetCartByUserId(userId);

            if (cart.CartHeader != null)
            {

                if (!string.IsNullOrEmpty(cart.CartHeader.CouponCode))
                {
                    var coupon = await _couponRepository.GetCoupon(cart.CartHeader.CouponCode);

                    if (coupon?.Code != null)
                    {
                        cart.CartHeader.DiscountAmount = coupon.DiscountAmount;
                    }
                }
                foreach (var detail in cart.CartDetails)
                {
                    cart.CartHeader.PurchaseAmount += (detail.Product.Price * detail.Count);
                }

                cart.CartHeader.PurchaseAmount -= cart.CartHeader.DiscountAmount;
            }

            return View(cart);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CartDTO cartDTO)
        {
            var userId = User.Claims.Where(u => u.Type == "sub")?.FirstOrDefault()?.Value;

            var cart = await _cartRepository.GetCartByUserId(userId);

            if (!ModelState.IsValid) {
                return View(cart);
            }

            OrderHeader order = new()
            {
                UserId = cart.CartHeader.UserId,
                FirstName = cartDTO.CartHeader.FirstName,
                LastName = cartDTO.CartHeader.LastName,
                OrderDetails = new List<OrderDetail>(),
                CardNumber = cartDTO.CartHeader.CardNumber,
                CouponCode = cart.CartHeader.CouponCode,
                CVV = cartDTO.CartHeader.CVV,
                DiscountAmount = cartDTO.CartHeader.DiscountAmount,
                Email = cartDTO.CartHeader.Email,
                ExpireDate = cartDTO.CartHeader.ExpireDate,
                OrderTime = DateTime.Now,
                PurchaseAmount = cartDTO.CartHeader.PurchaseAmount,
                PaymentStatus = false,
                Phone = cartDTO.CartHeader.Phone,
                DateTime = DateTime.Now
            };

            foreach (var cartDetail in cart.CartDetails)
            {
                OrderDetail detail = new()
                {
                    ProductId = cartDetail.ProductId,
                    ProductName = cartDetail.Product.Name,
                    Price = cartDetail.Product.Price,
                    Count = cartDetail.Count,
                };
                order.CartTotalItems += cartDetail.Count;
                order.OrderDetails.Add(detail);
            }

            var orderDb = await _orderRepository.AddOrder(order);
            
            await _cartRepository.ClearCart(userId);

            this.SendEmail(order);

            await _orderRepository.UpdateOrderPaymentStatus(orderDb.Id, true);

            return RedirectToAction(nameof(Confirmation));
        }

        [HttpGet]
        public IActionResult Confirmation()
        {
            return View();
        }

        private void SendEmail(OrderHeader order)
        {
            SmtpClient smtpClient = new SmtpClient("sandbox.smtp.mailtrap.io", 2525)
            {
                Credentials = new NetworkCredential("23427d12493947", "1d387ba2cd6e0c"),
                EnableSsl = true
            };
            MailMessage mail = new MailMessage
            {
                From = new MailAddress("geekshopping@gmail.com"),
                Subject = "GeekShopping - Order Notification",
                Body = $"Order - {order.Id} has been created successfully.",
                IsBodyHtml = false
            };
            mail.To.Add(order.Email);
            smtpClient.Send(mail);
        }
    }
}

GeekShopping/GeekShopping.Web/Controllers/CouponController.cs
using GeekShopping.Web.Models;
using GeekShopping.Web.Interfaces;
using GeekShopping.Web.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;

namespace GeekShopping.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }
        public async Task<IActionResult> Index()
        {
            var accessToken = await GetAccessToken();
            var coupons = await _couponService.GetCoupons(accessToken);
            return View(coupons);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Coupon coupon)
        {
            if (ModelState.IsValid)
            {
                var accessToken = await GetAccessToken();
                var response = await _couponService.Create(coupon, accessToken);
                if (response != null) return RedirectToAction(nameof(Index));
            }
            return View(coupon);
        }
        public async Task<IActionResult> Update(int id)
        {
            var accessToken = await GetAccessToken();
            var coupon = await _couponService.GetCoupon(id, accessToken);
            return View(coupon);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Update(Coupon coupon)
        {
            if (ModelState.IsValid)
            {
                var accessToken = await GetAccessToken();
                var response = await _couponService.Update(coupon, accessToken);
                if (response != null) return RedirectToAction(nameof(Index));
            }
            return View(coupon);
        }
        [HttpPost]
        [Authorize(Roles = Role.Admin)]
        public async Task<IActionResult> Delete(int id)
        {
            var accessToken = await GetAccessToken();
            var response = await _couponService.Delete(id, accessToken);
            if (response) return RedirectToAction(nameof(Index));
            return View();
        }

        private Task<string> GetAccessToken()
        {
            return HttpContext.GetTokenAsync("access_token");
        }
    }
}

GeekShopping/GeekShopping.Web/Controllers/OrderController.cs
using GeekShopping.Web.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GeekShopping.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");
            var userId = User.Claims.Where(u => u.Type == "sub")?.FirstOrDefault()?.Value;
            var orders = await _orderService.GetOrdersByUserId(userId, accessToken);
            return View(orders);
        }
    }
}

GeekShopping/GeekShopping.Web/Controllers/ProductController.cs
using GeekShopping.Web.Interfaces;
using GeekShopping.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using GeekShopping.Web.Utils;
using Microsoft.AspNetCore.Authentication;
using GeekShopping.Web.DTO;

namespace GeekShopping.Web.Controllers
{
  public class ProductController : Controller
  {
    private readonly IProductRepository _productRepository;

    public ProductController(IProductRepository productRepository)
    {
        _productRepository = productRepository;
    }

    public async Task<IActionResult> Index()
    {
      var products = await _productRepository.FindAll();
      return View(products);
    }

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Create(ProductDTO product)
    {
      if (ModelState.IsValid)
      {
        var response = await _productRepository.Create(product);
        if (response != null) return RedirectToAction(nameof(Index));
      }
      return View(product);
    }

    public async Task<IActionResult> Update(int id)
    {
      var product = await _productRepository.FindById(id);
      return View(product);
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Update(ProductDTO product)
    {
      if (ModelState.IsValid)
      {
        var response = await _productRepository.Update(product);
        if (response != null) return RedirectToAction(nameof(Index));
      }
      return View(product);
    }

    [Authorize]
    public async Task<IActionResult> Delete(int id)
    {
      var model = await _productRepository.FindById(id);
      if (model != null) return View(model);
      return NotFound();
    }

    [HttpPost]
    [Authorize(Roles = Role.Admin)]
    public async Task<IActionResult> Delete(Product product)
    {
      var response = await _productRepository.Delete(product.Id);
      if (response) return RedirectToAction(nameof(Index));
      return View(product);
    }
  }
}

GeekShopping/GeekShopping.Web/Views/Shared/Redirect.cshtml
@model GeekShopping.Web.Authentication.RedirectViewModel

<div class="redirect-page">
    <div class="lead">
        <h1>You are now being returned to the application</h1>
        <p>Once complete, you may close this tab.</p>
    </div>
</div>

<meta http-equiv="refresh" content="0;url=@Model.RedirectUrl" data-url="@Model.RedirectUrl">
<script src="~/js/signin-redirect.js"></script>

GeekShopping/GeekShopping.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] GeekShopping.Web</title>
  <link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon">
  <link rel="icon" href="/images/favicon.png" type="image/x-icon">
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <link rel="stylesheet" href="~/GeekShopping.Web.styles.css" asp-append-version="true" />
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
          <img src="/images/geek_shopping.png" width="185px" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <partial name="_LoginPartial"/>
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                  <i class="fas fa-shopping-cart"></i> Cart
              </a>
            </li>
             <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">
                  <i class="fas fa-truck"></i> Orders
              </a>
            </li>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {              
              <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Coupon" asp-action="Index">Coupon</a>
              </li>
            }
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2024 - GeekShopping.Web
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/ef27dc1cf3.js" crossorigin="anonymous"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

GeekShopping/GeekShopping.Web/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}